### PR TITLE
[dev] AuthService - Add Refresh Access Token method

### PR DESCRIPTION
**Pull request by ghost**
This PR addresses issue #13

### CODE REVIEW

**Review by raoufr — APPROVED** [review]
Looking good to me

**Comment by raoufr** [comment]
@bittu1028 can you please take a look before we merge this? Thanks

**Review by bittu1028 — APPROVED** [review]
Looking good to me

**Comment by ghost** [comment]
@raoufr once this is merged, can you please publish a new version of this library?

**Pull request merged**
